In [ ]:
import numpy as np

print("СОЗДАНИЕ МАССИВОВ\n")
print("1. Массив из списка:")

list_array = np.array([1, 2, 3, 4, 5])

print(f"list_array = {list_array}")
print("\n3. Массив нулей:")

zeros_array = np.zeros(5)

print(f"zeros_array = {zeros_array}")
print("\n4. Массив единиц:")

ones_array = np.ones((3, 3))

print(f"ones_array = \n{ones_array}")
print("\n5. Массив с помощью arange:")

range_array = np.arange(0, 10, 2)

print(f"range_array = {range_array}")

print("\nАТРИБУТЫ МАССИВОВ\n")

print("\n2. Двумерный массив из списка списков:")

matrix_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(f"{matrix_2d}")
print("Атрибуты matrix_2d:")
print(f"Форма (shape): {matrix_2d.shape}")
print(f"Тип данных (dtype): {matrix_2d.dtype}")
print(f"Размерность (ndim): {matrix_2d.ndim}")
print(f"Общее количество элементов (size): {matrix_2d.size}")

print("\nИНДЕКСИРОВАНИЕ И СРЕЗЫ\n")

demo_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(f"Исходный массив: {demo_array}")
print(f"\n1. Элемент с индексом 3: {demo_array[3]}")
print(f"2. Элемент с индексом -1 (последний): {demo_array[-1]}")
print(f"\n3. Срез [2:6]: {demo_array[2:6]}")
print(f"4. Срез [::2] (каждый второй элемент): {demo_array[::2]}")
print(f"5. Срез [1::3] (начиная с индекса 1, каждый третий): {demo_array[1::3]}")

print("\nЕКТОРНЫЕ ОПЕРАЦИИ\n")

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(f"Массив a: {a}")
print(f"Массив b: {b}")
print(f"\n1. Поэлементное сложение: {a + b}")
print(f"2. Поэлементное умножение: {a * b}")
print(f"3. Поэлементное вычитание: {b - a}")
print(f"4. Поэлементное деление: {b // a}")
print(f"\n5. Умножение на число (a * 2): {a * 2}")
print(f"6. Прибавление числа (b + 10): {b + 10}")

print("\nБАЗОВАЯ СТАТИСТИКА\n")

stats_array = np.array([12, 15, 18, 22, 25, 28, 32, 35, 38, 42])

print(f"Массив для статистики: {stats_array}")
print(f"\n1. Среднее значение (mean): {np.mean(stats_array)}")
print(f"2. Медиана (median): {np.median(stats_array)}")
print(f"3. Стандартное отклонение (std): {np.std(stats_array):.2f}")
print(f"4. Дисперсия (var): {np.var(stats_array):.2f}")
print(f"5. Минимальное значение (min): {np.min(stats_array)}")
print(f"6. Максимальное значение (max): {np.max(stats_array)}")
print(f"7. Сумма всех элементов (sum): {np.sum(stats_array)}")
print(f"8. Произведение всех элементов (prod): {np.prod(stats_array)}")


СОЗДАНИЕ МАССИВОВ

1. Массив из списка:
list_array = [1 2 3 4 5]

3. Массив нулей:
zeros_array = [0. 0. 0. 0. 0.]

4. Массив единиц:
ones_array = 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

5. Массив с помощью arange:
range_array = [0 2 4 6 8]

АТРИБУТЫ МАССИВОВ


2. Двумерный массив из списка списков:
[[1 2 3]
 [4 5 6]]
Атрибуты matrix_2d:
Форма (shape): (2, 3)
Тип данных (dtype): int64
Размерность (ndim): 2
Общее количество элементов (size): 6

ИНДЕКСИРОВАНИЕ И СРЕЗЫ

Исходный массив: [ 10  20  30  40  50  60  70  80  90 100]

1. Элемент с индексом 3: 40
2. Элемент с индексом -1 (последний): 100

3. Срез [2:6]: [30 40 50 60]
4. Срез [::2] (каждый второй элемент): [10 30 50 70 90]
5. Срез [1::3] (начиная с индекса 1, каждый третий): [20 50 80]

ЕКТОРНЫЕ ОПЕРАЦИИ

Массив a: [1 2 3 4]
Массив b: [5 6 7 8]

1. Поэлементное сложение: [ 6  8 10 12]
2. Поэлементное умножение: [ 5 12 21 32]
3. Поэлементное вычитание: [4 4 4 4]
4. Поэлементное деление: [5 3 2 2]

5. Умножение на число (a * 2): [2 4